version: '3'

services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/data/portainer:/data
    labels:
      - "traefik.domain=cloud.serubin.net"
      - "traefik.enable=true"
      - "traefik.port=9000"

